### ISSUE TITLE
Pro controller

### ISSUE THREAD

**Issue by xNeptune** [joffnerd/botw-trainer#133]
Selecting Pro Controller as the controller type doesn't allow Speed and Moon Jump to work properly (Any cheat that requires a button to be pressed)

**Comment by xNeptune** [comment]
Any type of quick fix I could use for this?

**Comment by skoolzout1** [comment]
The address that was being used for the pro controller changed over the patch. Until someone posts the new address (it's somewhere between 10200000-10400000) you'll have to wait or use the gamepad.

**Comment by skoolzout1** [comment]
Also, Panda, if you read this. I'd recommend modifying the readme to mention that The tcpgecko installer actually tells you your wiis ip. Since it seems like the most common problem people have is trying to connect because they don't know their ip. No additional programs or effort is needed besides just taking note of your ip before pressing A to install tcpgecko

**Comment by joffnerd** [comment]
Thanks mate, I direct realise pro address changed. Will amend in the morning
