### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by ThePsycrow** [joffnerd/botw-trainer#142]
Hey Joff,
Really dumb question.  I don't know much about coding but am curious about poking around with this.  I see you made it open source, so people could download and compile themselves.  What exactly is used for making/compiling this?  Like I know a little about Gecko so let's say I learned somehow that changing one value to something else had a different kind of effect, and I changed it in your source files before compiling so it could have a new effect.  How/what would I be using to compile the files with?  Is there a helpful link to the compiler or its instructions?
Thanks!

**Comment by skoolzout1** [comment]
Use Microsoft Visual Studio 2015 Community edition. you just need to make a microsoft account in order to use it, which doesnt take long. then you can download the source files, and open the project by double-clickling the BotwTrainer.sln file. This opens up the whole project, you can look around and edit all the source files you want and when you want to try it out you can just press debug and itll build your version

**Comment by ThePsycrow** [comment]
Thanks!  Gotcha

**Comment by joffnerd** [comment]
Yeah, you can just download the source and build it in VS 2015 as skoolzout said. Doesn't offer any advantage but you can mess with the code and see how it works.
