### ISSUE TITLE
Infinite Health option does not fully protect you in all cases in the latest trainer

### ISSUE THREAD

**Issue by doctahoo** [joffnerd/botw-trainer#159]
Hi,

I 'm playing Master Mode on a PAL Wii U and yesterday I tried your latest trainer (v4.1.2). It worked well in general, with one exception. It is the Infinite Health option. Apparently, it protects Link from losing hearts in most cases, but not in all. More specifically, it does not seem to work properly when an enemy hits Link with a bomb arrow from far away or when he is hit by a Lionel blow.

Is there a way to fix this so that the option works in all cases? (I think this may be a PAL issue with skoolzout1's code).

Thank you in advance and keep up the good work!

**Comment by windygeko** [comment]
No offense bud but the "infinite health" cheat never worked in ALL cases,
falling damage equal to 120+ will still kill you, certain attacks that
could be considered one hit kills will still kill your and crush damage
still applies, just be a little more careful or make better use of moon
jump that's honestly what I had to do

**Comment by doctahoo** [comment]
I see. I didn't know it NEVER worked in all cases!  ;-O

Ok. Thank you. I suppose there is no other way than try to avoid some very specific blows... Bummer.

**Comment by windygeko** [comment]
It's okay man me neither but there are very specific instances you can die,
codes aren't perfect but we always find work arounds ;3

**Comment by skoolzout1** [comment]
The trainer is effectively writing to your health address insanely fast. When you get hit with a regular attack, you actually technically still lose the amount of hearts dealt by the attack, but your hearts are filled back up faster than a single frame even passes by in the game. So if you get hit by a move that deals more than your current amount of health, the game triggers the death  sequence, this is often calculated before the hearts display is ever updated..

You can use the Mipha's grace code to aid with this since Mipha's grace will always restore your health regardless of how you die.

**Comment by EpicLPer** [comment]
Is there a way to constantly activate (even without pressing ZL) the shield special thingy there where every damage gets blocked? Not sure what that translates to in English.

**Comment by doctahoo** [comment]
Thanks, skoolzout1. I will combine some of your codes to try to get a similar effect to perfect immunity. :-)
