### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Darkaim63** [joffnerd/botw-trainer#165]
Game crashes on loading the codes, which codes work and which don't?

**Comment by skoolzout1** [comment]
Well. They should all work but this update introduced lots of issues. When I made the codes I tested them all for 5 hours of gameplay with no issues. So I assumed they'd be fairly stable.
The only way I can fix them is if I know which codes are causing issues and I also get a full game dump of the game when codes are not working.
Otherwise I can't do anything

**Comment by Darkaim63** [comment]
All the codes except for Moon Jump instantly crash my game

**Comment by skoolzout1** [comment]
Alright well download Jgecko if you don't have it and dump your full game from 10000000 to 4C8A0000 and send it to me

**Comment by Darkaim63** [comment]
Can't dump game, I get a stack error on my WiiU

**Comment by skoolzout1** [comment]
You need to update TCPgecko. Click the tcp gecko installer button in the external tools in Jgecko and extract the folder into wiiu/apps on your sd card. And delete the old TCPgecko folder while you're there since you don't need it

**Comment by Darkaim63** [comment]
The newest version is 2.3 correct? I currently have that installed but it will not let me dump the game. Does it not work for US version of the game?

**Comment by skoolzout1** [comment]
Idk what the latest version is but you must be doing something wrong along the way if the Wii crashes. You just connect the same way as the trainer to Jgecko and go to the dump tab
