### ISSUE TITLE
botw trainer exception type dsi occurred

### ISSUE THREAD

**Issue by badger3232** [joffnerd/botw-trainer#176]
hey i was just wondering about the error code i get when i try to connect the trainer to botw ( most resent update )

**Comment by Targren** [comment]
The trainer doesn't support 1.3.3 yet. Wait for an update.

**Comment by badger3232** [comment]
okay.Thanks

**Comment by DopeOE** [comment]
Yea i was disappointed when i found out the trainer didnt work for the new update but its probably because they added 5 new outfits to the game

**Comment by Targren** [comment]
@DopeOE The trainer will stop working after every pretty much any update, since changing the code alters the memory addresses that the trainer manipulates. It'll probably take at least a few weeks for the new codes to be updated, and then some time after that for the trainer itself. 

The moral: Don't update if you want to keep using trainers.

**Comment by DopeOE** [comment]
Ok yea @Targren i figured that much my flashdrives keep breaking and i only have a 8 gig wii u so i had to update it to play it but i can wait for the new trainer.
