### ISSUE TITLE
New update: 1.4.1, update please.

### ISSUE THREAD

**Issue by Nihejz** [joffnerd/botw-trainer#184]
Will they update to version 1.4.1?
yes, please.
Thank you!

**Comment by ashieo1130** [comment]
I don't know. I hope to god that they do. but with all the updates coming out, they are likely working as hard as they can. Each update code changes and it will crash upon connection. yada, yada, basically, it takes a couple of weeks for just one update, and with how many came out, plus the dlc's, its gonna take a while. I only got to use it for three hours before my wii u updated and I haven't been able to use it since the 30th, which sucks, because this is the greatest thing since sliced bread.

**Comment by joffnerd** [comment]
I haven't bothered updating anything due to constant version updates. When we finally hit a stable patch with no more DLC i will try to update.

**Comment by micha1987** [comment]
@ashieo1130 
You can use this for editing you're savegame:

http://www.marcrobledo.com/savegame-editors/zelda-botw/

**Comment by Endar-Marit** [comment]
@joffnerd It's been 2 weeks without any updates to the game, do you think they have it at a stable release yet or are you going to wait a little longer? Just curious is all :)

**Comment by ashieo1130** [comment]
@micha1987 where do i get my savegame on the sd card? Thanks!

**Comment by micha1987** [comment]
I use Savemii Mod.

**Comment by ashieo1130** [comment]
I think I've heard of it, could You send me a working like with a working
version?  I appreciate it!
