### ISSUE TITLE
I don't like the new code system

### ISSUE THREAD

**Issue by thefinalflash060** [joffnerd/botw-trainer#188]
I like more the old code system

**Comment by joffnerd** [comment]
Well when you have come up with all the code required for 1.4.1 i will gladly implement it

**Comment by Shaza1991** [comment]
You could always go back to the old code system that everyone liked

**Comment by rabbitt** [comment]
@thefinalflash060 / @Shaza1991  - The code is here and easy to clone/fork. I'd suggest either submitting a PR with the changes you'd like, or forking and starting your own project if you don't like the direction that @joffnerd has taken. Complaining about a free application that a developer has chosen to share with you (for free!) does little to persuade the developer to make the changes you desire. 

Moreover, from a programming perspective, decoupling the codes makes a ton of sense and means that, in the future, the app won't have to be updated every time the game itself gets patched. That's actually good for you because then all you have to wait for is someone to publish the codes and you're good to go again. 

Now what would make this perfect, IMHO, is if the item (and similar) addresses weren't hard-coded, but stored in a separate config file - this would make the platform itself stable, requiring only simple configuration changes when the game is updated. Not only that, but it would make it easier for people to submit PR's with the updated addresses if they could just update a config file; ie., they wouldn't have to know C# to contribute, or help others get the app running again.

**Comment by joffnerd** [comment]
What rabbitt said...

**Comment by thefinalflash060** [comment]
So, it's there a way to go back to the old code system?

**Comment by thefinalflash060** [comment]
If there is a way, please tell me how to do it

**Comment by joffnerd** [comment]
Yeah, follow these instructions:

https://www.lifewire.com/how-to-format-c-drive-2626123

**Comment by thefinalflash060** [comment]
Thanks :)

**Comment by Shaza1991** [comment]
@thefinalflash060 When you figure out how to go back to the old cheat system can you please give me it so I can go back to that old cheat system

**Comment by joffnerd** [comment]
Not going to happen guys, **_learn_** how to use whats available.
