### ISSUE TITLE
kinda sad about the codes tab

### ISSUE THREAD

**Issue by YokujinKaze** [joffnerd/botw-trainer#191]
back then we had so many more options on how many rupees, mons we wanted or set certain values like walking speed or set the amount of weapons you want to carry etc

**Comment by rabbitt** [comment]
The problem is that, with each new release of the game (i.e., Zelda: BOTW), those codes have to change - which means that @joffnerd either has to find all the new memory locations himself, or wait until someone else provides them. That isn't fair to himself, or to others using the trainer. It is far more useful to have the codes decoupled from the trainer so that you can continue to use the trainer *regardless* of the particular game version - that is, you don't have to wait for @joffnerd to release a new version every time there's a new game. This allows you to continue to use the trainer, though with the caveat that you have wait for someone to post codes relevant to the version of the game you are running.

Lastly, and more importantly, while it might seem like he has nothing better to do than to pander to every request out there, keep in mind - when someone creates something and shares it online, they are doing it first and foremost for themselves (likely because he has the game, or because he has the "itch" that needs scratching, or both). You are reaping the benefits of someone who is gracious enough to share his work - remember that when complaining.

p.s. If you really like the old menu, you can always use the old version of the trainer and downgrade (likely by reinstalling) the game to a version that works with it. Or, optionally, you can always use [savemii](https://www.reddit.com/r/WiiUHacks/comments/6vfm75/tutorial_importing_wii_u_saves_with_savemii_mod/) and the [Zelda: BoTW Savegame Editor](http://www.marcrobledo.com/savegame-editors/zelda-botw/).
