### ISSUE TITLE
Linux Support ?

### ISSUE THREAD

**Issue by Crashdummyy** [joffnerd/botw-trainer#4]
Is there a way to start it with Linux ?
Wine / Mono doesn't seem to work :/

**Comment by joffnerd** [comment]
Hmm I am not sure. It's built in c# in Visual Studio 2013
Targeting Net Framework 4.5

Sorry I have never tried Wine / Mono. Do you get a specific error?

**Comment by Crashdummyy** [comment]
Sadly not ..
Trying few things out maybe I'm on the wrong .Net version

**Comment by Crashdummyy** [comment]
Okay aparently it's a Linux problem due to the lack of dotnet45 compatibility :/
I will close here

**Comment by joffnerd** [comment]
What version does it support?

**Comment by jqueuniet** [comment]
Just to chime in, this isn't due to 4.5 .NET compatibility, more likely due to the fact Mono doesn't implement WPF at the moment (a 3.0 .NET feature it seems), and has no plan to implement it. So, unless you have a plan not to use WPF, I don't see a way out of this, sadly.

You can see the compatibility status there : http://www.mono-project.com/docs/about-mono/compatibility/

The current error is : 

`The entry point method could not be loaded due to Could not load file or assembly or one of its dependencies. assembly:PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:<unknown type> member:<none>`

Not much luck with the officiel .NET runtime either, but it's still really fresh at the moment, so who knows, maybe I did something wrong.

`A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/johann/Downloads'.`

**Comment by jqueuniet** [comment]
Apparently, the official .NET open-source project is mostly focused on core libraries, doesn't have a plan for WPF either and likely never will since it's an abstraction layer for Win32 and DirectX, making it a real PITA to port.

For cross-platform GUI toolkits, there's a list among the Mono project pages : http://www.mono-project.com/docs/gui/
