### ISSUE TITLE
Connecting brings issues

### ISSUE THREAD

**Issue by Fiddadle** [joffnerd/botw-trainer#91]
I've seen from other issue posts that the trainer has broken from the latest update but I was wondering when people encounter the error. Is it when trying to change values or when connecting because as soon as I  hit, connect the game shows a black screen with white text on it. I wish all the best to the dev team and hope you fix it soon.

I was also wondering if it is possible to downgrade without it prompting you to update?

**Comment by xNeptune** [comment]
The trainer "breaks" as soon as you attempt to connect to the wii u. As for downgrading it IS possible however you would have to revert back to the stock version of the game, due to the software update data being all within one file. I'm sure there are other methods to remove the most recent update but I'm not aware of one at the moment however I will be searching around.

**Comment by joffnerd** [comment]
Closing all issues which are probably related to 1.1.1
